import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import { CameraIcon } from '../icons';

const AIImageGenerator: React.FC = () => {
    const [prompt, setPrompt] = useState('');
    const [imageUrl, setImageUrl] = useState<string | null>(null);
    const [isGenerating, setIsGenerating] = useState(false);
    const [error, setError] = useState('');

    const handleGenerate = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!prompt.trim()) return;
        setIsGenerating(true);
        setImageUrl(null);
        setError('');
        try {
            const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
            const response = await ai.models.generateImages({
                model: 'imagen-4.0-generate-001',
                prompt: prompt,
                config: {
                  numberOfImages: 1,
                  outputMimeType: 'image/png',
                },
            });

            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            const url = `data:image/png;base64,${base64ImageBytes}`;
            setImageUrl(url);

        } catch (err) {
            console.error("Error generating image:", err);
            setError("Sorry, I couldn't generate an image for that prompt. It might be too complex or against the safety policy.");
        } finally {
            setIsGenerating(false);
        }
    };

    return (
        <div>
            <form onSubmit={handleGenerate} className="flex flex-col sm:flex-row items-center gap-4">
                <input
                    type="text"
                    value={prompt}
                    onChange={e => setPrompt(e.target.value)}
                    placeholder="e.g., A photorealistic image of Albert Einstein in his study"
                    className="flex-grow w-full p-2 border border-gray-600 rounded-lg bg-surface text-onBackground focus:ring-teal-500 focus:border-teal-500"
                />
                <button type="submit" disabled={isGenerating || !prompt.trim()} className="w-full sm:w-auto px-6 py-2 bg-gradient-to-r from-teal-600 to-teal-500 text-white font-semibold rounded-lg hover:from-teal-500 hover:to-teal-400 transition transform active:scale-95 disabled:opacity-50 flex items-center justify-center gap-2">
                     <CameraIcon className="w-5 h-5" />
                    {isGenerating ? 'Generating...' : 'Generate'}
                </button>
            </form>
            {isGenerating && <div className="mt-4 text-center text-onSurface">AI is creating your image... This may take a moment.</div>}
            {error && <p className="mt-4 text-center text-danger">{error}</p>}
            
            {imageUrl && (
                <div className="mt-6 animate-fadeInUp">
                    <h3 className="text-lg font-bold text-onBackground mb-2 text-center">Result:</h3>
                    <div className="flex justify-center">
                        <img src={imageUrl} alt="Generated by AI" className="max-h-96 rounded-lg shadow-lg" />
                    </div>
                </div>
            )}
        </div>
    );
};

export default AIImageGenerator;